### ISSUE TITLE
exit() function.

### ISSUE THREAD

**Issue by TimaFrolov** [ruc-math-1/RuC#8]
There are lots of places where the exit() function is used, so we have to implement it

**Comment by TimaFrolov** [comment]
Realised that exist t_exit() function that can be used instead of exit()

**Comment by georgiy-belyanin** [comment]
Probably, this would be a good idea, cause t_exit() is used for threads while exit terminates the whole process.

**Comment by TimaFrolov** [comment]
But we have only one thread in compiler anyway, so it doesn't really matter
